services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
    ports:
      - "80:80"
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - BACKEND_ALB_URL=${BACKEND_ALB_URL}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3200:3200"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}